// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ReceptContext))]
    [Migration("20260519084259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Apotek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apoteker");
                });

            modelBuilder.Entity("Models.Lægehus", b =>
                {
                    b.Property<string>("Ydernummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ydernummer");

                    b.ToTable("Lægehuse");
                });

            modelBuilder.Entity("Models.Ordination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntalForetagneUdleveringer")
                        .HasColumnType("int");

                    b.Property<int>("AntalUdleveringer")
                        .HasColumnType("int");

                    b.Property<string>("Dosering")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lægemiddel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ordinationer");
                });

            modelBuilder.Entity("Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ErLukket")
                        .HasColumnType("bit");

                    b.Property<string>("LægehusYdernummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OprettetDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientCpr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LægehusYdernummer");

                    b.ToTable("Recepter");
                });

            modelBuilder.Entity("Models.Ordination", b =>
                {
                    b.HasOne("Models.Recept", null)
                        .WithMany("Ordinationer")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Recept", b =>
                {
                    b.HasOne("Models.Lægehus", null)
                        .WithMany("Recepter")
                        .HasForeignKey("LægehusYdernummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Lægehus", b =>
                {
                    b.Navigation("Recepter");
                });

            modelBuilder.Entity("Models.Recept", b =>
                {
                    b.Navigation("Ordinationer");
                });
#pragma warning restore 612, 618
        }
    }
}
