// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ReceptContext))]
    partial class ReceptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Apotek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apoteker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Hovedgaden 2",
                            Navn = "Løve Apoteket"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Stationen 4",
                            Navn = "Ørne Apoteket"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Torvet 2",
                            Navn = "Solsikke Apoteket"
                        });
                });

            modelBuilder.Entity("Models.Lægehus", b =>
                {
                    b.Property<string>("Ydernummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ydernummer");

                    b.ToTable("Lægehuse");

                    b.HasData(
                        new
                        {
                            Ydernummer = "123456",
                            Adresse = "Torvet 1",
                            Navn = "Lægerne i Centrum"
                        },
                        new
                        {
                            Ydernummer = "654321",
                            Adresse = "Skovvejen 5",
                            Navn = "Skovvejens Lægehus"
                        },
                        new
                        {
                            Ydernummer = "112233",
                            Adresse = "Vesterbro 10",
                            Navn = "Vestbyens Klinik"
                        });
                });

            modelBuilder.Entity("Models.Ordination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntalForetagneUdleveringer")
                        .HasColumnType("int");

                    b.Property<int>("AntalUdleveringer")
                        .HasColumnType("int");

                    b.Property<string>("Dosering")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lægemiddel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ordinationer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AntalForetagneUdleveringer = 0,
                            AntalUdleveringer = 3,
                            Dosering = "2 stk 3 gange daglig",
                            Lægemiddel = "Pamol 500mg",
                            ReceptId = 1
                        },
                        new
                        {
                            Id = 2,
                            AntalForetagneUdleveringer = 0,
                            AntalUdleveringer = 1,
                            Dosering = "1 stk efter behov",
                            Lægemiddel = "Ipren 200mg",
                            ReceptId = 1
                        },
                        new
                        {
                            Id = 3,
                            AntalForetagneUdleveringer = 2,
                            AntalUdleveringer = 2,
                            Dosering = "1 stk dagligt",
                            Lægemiddel = "Alnok 10mg",
                            ReceptId = 2
                        });
                });

            modelBuilder.Entity("Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ErLukket")
                        .HasColumnType("bit");

                    b.Property<string>("LægehusYdernummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OprettetDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientCpr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LægehusYdernummer");

                    b.ToTable("Recepter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ErLukket = false,
                            LægehusYdernummer = "123456",
                            OprettetDato = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCpr = "1212121212"
                        },
                        new
                        {
                            Id = 2,
                            ErLukket = false,
                            LægehusYdernummer = "654321",
                            OprettetDato = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCpr = "1212121212"
                        },
                        new
                        {
                            Id = 3,
                            ErLukket = true,
                            LægehusYdernummer = "112233",
                            OprettetDato = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCpr = "1122334455"
                        });
                });

            modelBuilder.Entity("Models.Ordination", b =>
                {
                    b.HasOne("Models.Recept", null)
                        .WithMany("Ordinationer")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Recept", b =>
                {
                    b.HasOne("Models.Lægehus", null)
                        .WithMany("Recepter")
                        .HasForeignKey("LægehusYdernummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Lægehus", b =>
                {
                    b.Navigation("Recepter");
                });

            modelBuilder.Entity("Models.Recept", b =>
                {
                    b.Navigation("Ordinationer");
                });
#pragma warning restore 612, 618
        }
    }
}
